-- V9: 기본키를 UUID v4 에서 BIGINT 순번으로 (2026-09-13)
--
-- 왜 드롭하고 다시 만드나
--   기본키 타입을 바꾸는 것은 그 키를 가리키는 FK 를 전부 함께 바꾸는 일이다.
--   FK 가 15개라 컬럼 추가 → 백필 → 재지정 → 스왑을 15번 반복해야 하는데,
--   보존할 데이터가 데모 봇과 테스트 계정뿐이라 그 복잡도를 살 이유가 없다.
--   🔴 이 마이그레이션은 <기존 데이터를 전부 버린다>. 2026-09-13 에 알고 택했다.
--
-- 왜 GENERATED BY DEFAULT AS IDENTITY 인가
--   ① 번호를 매기는 주체가 DB 하나여야 한다. Spring 과 Python 이 같은 테이블에 쓰는데
--      양쪽이 각자 번호를 만들면 반드시 충돌한다.
--   ② ALWAYS 가 아니라 BY DEFAULT 인 이유: 테스트가 id 를 명시해 넣는 자리가 있고,
--      아래 데모 봇 시드도 id = 1 을 직접 넣는다. ALWAYS 면 그게 막힌다.
--   ③ BIGSERIAL 이 아닌 이유: IDENTITY 가 SQL 표준이고, 시퀀스가 컬럼에 묶여
--      테이블을 지울 때 함께 사라진다(BIGSERIAL 은 시퀀스가 남을 수 있다).

DROP TABLE IF EXISTS eval_results, eval_questions, eval_runs, doc_conflicts,
                     messages, conversations, chunks, documents,
                     billing_methods, usage_events, bots, users CASCADE;

CREATE TABLE users (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                VARCHAR(255) UNIQUE NOT NULL,
  password_hash        VARCHAR(255) NOT NULL,
  name                 VARCHAR(50),
  plan                 VARCHAR(16) NOT NULL DEFAULT 'free',
  billing_customer_key VARCHAR(50) NOT NULL UNIQUE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_users_plan CHECK (plan IN ('free', 'pro'))
);

CREATE TABLE bots (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT REFERENCES users(id) ON DELETE CASCADE,
  name             VARCHAR(100) NOT NULL,
  public_key       VARCHAR(32) UNIQUE NOT NULL,
  system_prompt    TEXT,
  welcome_message  TEXT NOT NULL DEFAULT '무엇을 도와드릴까요?',
  fallback_message TEXT NOT NULL DEFAULT '문서에서 답을 찾지 못했어요. 담당자에게 문의해주세요.',
  allowed_origins  TEXT[],
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE documents (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id        BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  filename      VARCHAR(255) NOT NULL,
  file_type     VARCHAR(10)  NOT NULL,
  status        VARCHAR(20)  NOT NULL DEFAULT 'pending',
  error_message TEXT,
  char_count    INT,
  chunk_count   INT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_documents_bot ON documents (bot_id);

CREATE TABLE chunks (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  bot_id      BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  chunk_index INT  NOT NULL,
  content     TEXT NOT NULL,
  embedding   VECTOR(1024),
  tokens      TEXT,
  meta        JSONB NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_chunks_bot ON chunks (bot_id);
CREATE INDEX idx_chunks_embedding ON chunks USING hnsw (embedding vector_cosine_ops);
COMMENT ON COLUMN chunks.embedding IS
  '@cf/baai/bge-m3 (1024차원). 모델을 바꾸면 반드시 전체 재임베딩할 것.';

CREATE TABLE conversations (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id     BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  session_id VARCHAR(64) NOT NULL,
  channel    VARCHAR(10) NOT NULL DEFAULT 'widget',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_conv_bot_session ON conversations (bot_id, session_id);

CREATE TABLE messages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role            VARCHAR(10) NOT NULL,
  content         TEXT NOT NULL,
  sources         JSONB,
  is_fallback     BOOLEAN NOT NULL DEFAULT false,
  feedback        SMALLINT,
  latency_ms      INT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_messages_conv ON messages (conversation_id);

CREATE TABLE eval_questions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id          BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  question        TEXT NOT NULL,
  ground_truth    TEXT NOT NULL,
  source_chunk_id BIGINT REFERENCES chunks(id) ON DELETE SET NULL,
  is_active       BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE eval_runs (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id           BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  config           JSONB,
  avg_faithfulness NUMERIC(4,3),
  avg_relevancy    NUMERIC(4,3),
  answered_rate    NUMERIC(4,3),
  status           VARCHAR(20) NOT NULL DEFAULT 'running',
  question_count   INT,
  scored_count     INT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON COLUMN eval_runs.question_count IS
  '이 실행이 대상으로 삼은 활성 질문 수. avg_* 를 해석하려면 반드시 필요한 분모.';
COMMENT ON COLUMN eval_runs.scored_count IS
  '실제로 채점된 질문 수. avg_faithfulness/avg_relevancy 의 진짜 분모.';

CREATE TABLE eval_results (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id           BIGINT NOT NULL REFERENCES eval_runs(id) ON DELETE CASCADE,
  question_id      BIGINT NOT NULL REFERENCES eval_questions(id) ON DELETE CASCADE,
  generated_answer TEXT,
  retrieved_chunks JSONB,
  faithfulness     NUMERIC(4,3),
  relevancy        NUMERIC(4,3),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE doc_conflicts (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id      BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  chunk_a_id  BIGINT NOT NULL REFERENCES chunks(id) ON DELETE CASCADE,
  chunk_b_id  BIGINT NOT NULL REFERENCES chunks(id) ON DELETE CASCADE,
  topic       TEXT NOT NULL,
  a_says      TEXT NOT NULL,
  b_says      TEXT NOT NULL,
  distance    REAL,
  status      VARCHAR(10) NOT NULL DEFAULT 'open',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_conflicts_bot_status ON doc_conflicts (bot_id, status);
CREATE UNIQUE INDEX uq_conflicts_pair ON doc_conflicts (bot_id, chunk_a_id, chunk_b_id);
COMMENT ON TABLE doc_conflicts IS
  '문서 간 사실 충돌. Python 이 임베딩으로 후보를 좁히고 judge 모델로 판정해 채운다.';
COMMENT ON COLUMN doc_conflicts.status IS
  'open | ignored | resolved | clear. 화면에 뜨는 것은 open 뿐이다.';

CREATE TABLE usage_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- 🔴 bots 를 FK 로 걸지 않는다. 봇이 지워져도 그 달 기록은 남아야 한다. (V5 와 같다)
  bot_id      BIGINT,
  kind        VARCHAR(20) NOT NULL,
  -- 🔴 messages.id 와 eval_runs.id 를 한 컬럼에 섞어 담는다.
  --    번호가 겹칠 수 있지만 UNIQUE 가 (kind, source_ref) 복합이라 서로 다른 행이다.
  source_ref  BIGINT NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_usage_source UNIQUE (kind, source_ref)
);
CREATE INDEX idx_usage_user_time ON usage_events (user_id, occurred_at);

CREATE TABLE billing_methods (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  billing_key_enc    VARCHAR(512) NOT NULL,
  issuer_code        VARCHAR(4)  NOT NULL,
  card_number_masked VARCHAR(20) NOT NULL,
  is_default         BOOLEAN NOT NULL DEFAULT false,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_billing_methods_default ON billing_methods (user_id) WHERE is_default;
CREATE INDEX idx_billing_methods_user_id ON billing_methods (user_id);

-- ── 공개 데모 봇 (V1 의 pk_local_dev 를 이어받는다) ──────────────
-- 이 봇은 로컬 개발용이 아니라 공개 /demo 화면이 fallback 으로 쓰는 봇이다.
-- 지우면 운영의 /demo 가 전부 fallback 이 된다 (AGENTS.md Flyway 규칙 4번).
INSERT INTO bots (id, name, public_key) VALUES (1, '테스트 봇', 'pk_local_dev');

-- 🔴 이 줄이 없으면 다음 봇 생성이 id = 1 로 시도돼 중복키로 실패한다.
--    id 를 명시해 넣으면 IDENTITY 시퀀스는 그 사실을 모르기 때문이다.
SELECT setval(pg_get_serial_sequence('bots', 'id'), 1, true);
